version: '3'
services:
  dev:
    image: node:7.7.2-alpine
    build: ./docker/dev
    volumes:
        - .:/usr/share/nginx/html/
        - ./docker/dev/nginx/:/etc/nginx/conf.d/
    ports: 
        - 8000:8000
        - 80:80